name: jhub
channels:
  - conda-forge
  - pytorch
dependencies:
  - jupyter
  - matplotlib
  - nltk
  - numpy>=1.16
  - pytorch>=1.0
  - pandas
  - python
  - scipy
  - spacy<2
  - tensorflow==1.13.1
  - tensorflow-estimator==1.13.0
  - pip==9.0.3
  - Keras==2.2.4
  - Keras-Applications==1.0.7
  - Keras-Preprocessing==1.0.9
